### ISSUE TITLE
Broken link in sphinx docs

### ISSUE THREAD

**Issue by Prooffreader** [marczz/rest-sphinx-memo#3]
On the page:

http://rest-sphinx-memo.readthedocs.io/en/latest/Sphinx.html

The link with the text 

There are very powerful directives in Sphinx for **documenting source code**

Leading to 

http://www.sphinx-doc.org/en/stable/markup/desc.html#module-specific-markup

Gives a 404 Not Found error.

**Comment by marczz** [comment]
Fixed in the commit https://github.com/marczz/rest-sphinx-memo/commit/e03ff0b24a26d943e17f87bc0956cb19161f26e0
